# Generated by Django 4.2.14 on 2024-08-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('incoming', '0002_alter_article_model_alter_article_type_delete_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_articles', to='inventory.model'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_articles', to='inventory.type'),
        ),
    ]
