# Generated by Django 4.2.14 on 2024-08-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_myuser_bio_myuser_date_of_birth_myuser_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='status',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
