# Generated by Django 4.2.14 on 2024-08-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='vnc',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
